fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\ORM\Entity\Organization\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

sensio_framework_extra:
    router:      { annotations: true }
    request:     { converters: true, auto_convert: true }
    view:        { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
    psr_message: { enabled: false }